// packages/create-app/templates/vue/src/App.vue
<style>
@import url("https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap");

.main {
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 2.2rem;
  text-align: center;
  color: white;
  background-color: #2a2938;
  font-family: "Jost", sans-serif;
  padding: 20px;
}
</style>

<template>
  <div class="main">
    <p>
      Get started by editing <code>src/App.vue</code>
    </p>
  </div>
</template>

// packages/create-app/templates/svelte/src/App.svelte
<style>
@import url("https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap");

.main {
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 2.2rem;
  text-align: center;
  color: white;
  background-color: #2a2938;
  font-family: "Jost", sans-serif;
  padding: 20px;
}
</style>

<div class="main">
  <p>
    Get started by editing <code>src/App.svelte</code>
  </p>
</div>
