// playground/src/vue/App.vue
<template>
  <h2>Vue.js Example</h2>
  <p class="msg">Count is {{ count }}</p>
  <button v-on:click="increase">Increase</button>
  <span style="padding: 8px;"></span>
  <button v-on:click="decrease">Decrease</button>
</template>

<style scoped>
  h2 {
    font-family: sans-serif;
    font-weight: normal;
  }

  .msg {
    font-family: sans-serif;
  }
</style>

<script>
  export default {
    data() {
      console.log('Source map test');
      return {
        count: 0
      }
    },
    methods: {
      increase() {
        this.count++;
      },
      decrease() {
        this.count--;
      }
    }
  }
</script>

// playground/src/react/App.jsx
import * as React from 'react';
import { useCounter } from './useCounter';

const Test = () => {
  const [count, increment, decrement] = useCounter(0);

  console.log('Source map test');

  return (
    <div>
      <p>Count is {count}</p>
      {/* <p>New content</p> */}
      <button onClick={increment}>Increase</button>
      <span style={{ width: 10, display: 'inline-block' }}></span>
      <button onClick={decrement}>Decrease</button>
    </div>
  )
}

export const App = () => (
  <div>
    <Test />
  </div>
)
