// playground/src/vue/App.vue
<template>
  <h2>Vue.js Example</h2>
  <p class="msg">Count is {{ count }}</p>
  <button v-on:click="increase">Increase</button>
  <span style="padding: 8px;"></span>
  <button v-on:click="decrease">Decrease</button>
</template>

<style scoped>
  h2 {
    font-family: sans-serif;
    font-weight: normal;
  }

  .msg {
    font-family: sans-serif;
  }
</style>

<script>
  export default {
    data() {
      console.log('Source map test');
      return {
        count: 0
      }
    },
    methods: {
      increase() {
        this.count++;
      },
      decrease() {
        this.count--;
      }
    }
  }
</script>

// playground/src/react-fast-refresh/App.js
import * as React from 'react';

export const App = () => {
  const [count, setCount] = React.useState(0);

  console.log('Source map test');

  return (
    <div>
      <p>Count is {count}</p>
      {/* <p>New content</p> */}
      <button onClick={() => setCount(count + 10)}>Increase</button>
      <button onClick={() => setCount(count - 10)}>Decrease</button>
    </div>
  )
}
